import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import NavBarClient from "@/components/nav/navbar-client";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/server/auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const session = await auth();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-4 max-w-5xl mx-auto`}
      >
        <SessionProvider session={session} >
          <NavBarClient />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
